version: "3"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"   

  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always    
    environment:
      - MONGODB_USER=admin
      - MONGOFB_DATABASE=sales
      - MONGODB_PASS=12345
    ports:
      - "27017:27017"
      - "27018:27018" 

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit 
    ports:
      - "5672:5672"
      - "15672:15672"
