INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1003, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1001, 'Crises nas Infinitas Terras', 1001, 1001, 10);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1002, 'Interestelar', 1002, 1002, 5);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1003, 'Harry Potter e a Pedra Filosofal', 1002, 1003, 3);